### ISSUE TITLE
Broken on the longest delay ever (2023-07-14)

### ISSUE THREAD

**Issue by kevinsumner** [Whenplane/whenplane#2]
whenplane.com stopped reporting lateness and is, instead, reporting time to next week's show. It happened around 8:30 PM Pacific time on 2023-07-14.

**Comment by kevinsumner** [comment]
Looks fixed as of b373bce!

**Comment by ajgeiss0702** [comment]
Leaving this open until I ensure this never happens again

**Comment by janishutz** [comment]
Are you sure that 5 hours is gonna be sufficient in all cases? I have just seen that you did that change, but wouldn't it be better to add some more code to have it always show the delay if the WAN show hadn't been live yet? I could open a PR to add that

**Comment by marlop352** [comment]
it probably will need a delay bigger than 24hrs for LTX WAN if it indeed happens on Saturday instead of on Friday, and today's already is getting close to being more than 5hrs late, so the cutoff probably should be changed to something like 12hrs(or 36 to account for LTX WAN) until the proper fix is done 😅

**Comment by janishutz** [comment]
Exactly. I am currently working on support for that as well as an easy way to add more data (essentially a page on my personal api where I know how everything works, lol)

**Comment by janishutz** [comment]
I have hit some major speed bumps, as I am not at all familiar with the backend this thing uses. What is needed in essence is just a way to check whether or not the show has been live in the last three days

**Comment by ajgeiss0702** [comment]
The site will now keep showing the show is late until a show starts. I should probably add a very large cutoff if they do eventually miss a show, but it should be fine for the foreseeable future since they seem to do everything possible not to miss a show.
